project_id = "avdkwrndyokuxrtpfrrt"

[functions]
  [functions.analyze-cv]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.flow-create]
    verify_jwt = false
  [functions.flow-webhook]
    verify_jwt = false
  [functions.job-matching]
    verify_jwt = false
