
ALTER TABLE public."Perfiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analisis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ofertas_laborales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_candidatos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suscripciones ENABLE ROW LEVEL SECURITY;
